src/Entity/Produtos.php
<?php

namespace App\Entity;

use App\Repository\ProdutosRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProdutosRepository::class)
 */
class Produtos
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=120)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descricao;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $id_image;

    /**
     * @ORM\ManyToOne(targetEntity=Categorias::class, inversedBy="Produtos")
     */
    private $categorias;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescricao(): ?string
    {
        return $this->descricao;
    }

    public function setDescricao(?string $descricao): self
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getIdImage(): ?bool
    {
        return $this->id_image;
    }

    public function setIdImage(?bool $id_image): self
    {
        $this->id_image = $id_image;

        return $this;
    }

    public function getCategorias(): ?Categorias
    {
        return $this->categorias;
    }

    public function setCategorias(?Categorias $categorias): self
    {
        $this->categorias = $categorias;

        return $this;
    }
}

src/Controller/ProdutosController.php
<?php

namespace App\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ProdutosRepository;
use App\Service\ContenuPageService;
use App\Service\ImagesService;
use Psr\Log\LoggerInterface;
use App\Repository\PagesRepository;
use App\Entity\Produtos;
use App\Repository\ImagesRepository;

class ProdutosController extends AbstractController
{
    const
    NOM_PAGE = 'home',
    SECTION_HEADER = 'header';
    
    private $is_debug;
    private $is_online;
    private $logger;
    
    
    public function __construct(bool $is_online, bool $is_debug, LoggerInterface $logger){
        $this->is_debug = $is_debug;
        $this->is_online = $is_online;
        $this->logger = $logger;
    }
    
    /**
     * @Route("/marinatraina", name="marinatraina")
     */
    public function index(ProdutosRepository $repo, PagesRepository $pagesRepo, ImagesService $imagesService, ContenuPageService $contenuPage): Response
    {
        $produtos = $repo->findAll();
        $pages = $pagesRepo->findAll();
        $images = $imagesService->getContenuHeader("accueil","highlights");
        $pageHeader = $contenuPage->getHeader(122, 3);
        
        return $this->render('produtos/index.html.twig', [
            'controller_name' => 'ProdutosController',
            'produtos' => $produtos,
            'pages' => $pages,
            'images' => $images,
            'header' => $pageHeader,
        ]);
    }
    
    /**
     * @Route("/produtos/detalhe/{id}", name="detalhe_produto")
     */
    public function detail(ProdutosRepository $repo, PagesRepository $pagesRepo, ImagesRepository $imagesRepo, Produtos $produto): Response
    {
        $produtos = $repo->findAll();
        $pages = $pagesRepo->findAll();
        $images = $imagesRepo->findByPageBlock("accueil","highlights");
        
        return $this->render('produtos/detail.html.twig', [
            'controller_name' => 'ProdutosController',
            'produtos' => $produtos,
            'produto' => $produto,
            'pages' => $pages,
            'images' => $images,
        ]);
    }
    
}

templates/produtos/detail.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
        <link rel="stylesheet" href="/assets/css/produtos.css">
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}



{% block body %}
<div id="main" class="wrapper style2">
					<div class="title">No Sidebar</div>
					<div class="container">

						<!-- Content -->
							<div id="content">
								<article class="box post">
									<header class="style1">
										<h2>Lorem ipsum dolor sit amet magna egestas<br class="mobile-hide" />
										morbi bibendum sed malesuada</h2>
										<p>Tempus feugiat veroeros sed nullam dolore</p>
									</header>
									<a href="#" class="image featured">
										<img src="images/pic01.jpg" alt="" />
									</a>
									
									{% block menuprodutos %}
									 
									
									{% endblock %}
									
									
							
							{% block detalheproduto %}
								<a href="{{ path('produtos') }}" class="image featured">
									>> return
								</a>
								<p>
								{{produto.categorias.nom}}
								</p>
								<p>
								{{produto.nom}}
								</p>
								<p>
								{{produto.descricao}}
								</p>
								<p>
								{{produto.idImage}}
								</p>
							{% endblock %}
								
									
								</article>
							</div>

					</div>
				</div>

			<!-- Highlights -->
				<section id="highlights" class="wrapper style3">
					<div class="title">The Endorsements</div>
					<div class="container">
						<div class="row aln-center">
							<div class="col-4 col-12-medium">
								<section class="highlight">
									<a href="#" class="image featured"><img src="images/pic02.jpg" alt="" /></a>
									<h3><a href="#">Aliquam diam consequat</a></h3>
									<p>Eget mattis at, laoreet vel amet sed velit aliquam diam ante, dolor aliquet sit amet vulputate mattis amet laoreet lorem.</p>
									<ul class="actions">
										<li><a href="#" class="button style1">Learn More</a></li>
									</ul>
								</section>
							</div>
							<div class="col-4 col-12-medium">
								<section class="highlight">
									<a href="#" class="image featured"><img src="images/pic03.jpg" alt="" /></a>
									<h3><a href="#">Nisl adipiscing sed lorem</a></h3>
									<p>Eget mattis at, laoreet vel amet sed velit aliquam diam ante, dolor aliquet sit amet vulputate mattis amet laoreet lorem.</p>
									<ul class="actions">
										<li><a href="#" class="button style1">Learn More</a></li>
									</ul>
								</section>
							</div>
							<div class="col-4 col-12-medium">
								<section class="highlight">
									<a href="#" class="image featured"><img src="images/pic04.jpg" alt="" /></a>
									<h3><a href="#">Mattis tempus lorem</a></h3>
									<p>Eget mattis at, laoreet vel amet sed velit aliquam diam ante, dolor aliquet sit amet vulputate mattis amet laoreet lorem.</p>
									<ul class="actions">
										<li><a href="#" class="button style1">Learn More</a></li>
									</ul>
								</section>
							</div>
						</div>
					</div>
				</section>
{% endblock %}

templates/produtos/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
        <link rel="stylesheet" href="/assets/css/produtos.css">
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

{% block header %}
	<section id="header" class="wrapper" style="width:600px">

		<!-- Logo -->
			<div id="logo" >
				<!--<h1><a href="index.html">{{ header.titre|raw }}</a></h1>
				<p>{{ header.contenu_text|striptags|markdown  }}</p>  -->
			</div>
	</section>
	
{% endblock %}

{% block body %}
<div id="main" class="wrapper style2">
					<div class="title">No Sidebar</div>
					<div class="container">

						<!-- Content -->
							<div id="content">
								<article class="box post">
									<header class="style1">
										<h2>Lorem ipsum dolor sit amet magna egestas<br class="mobile-hide" />
										morbi bibendum sed malesuada</h2>
										<p>Tempus feugiat veroeros sed nullam dolore</p>
									</header>
									<a href="#" class="image featured">
										<img src="images/pic01.jpg" alt="" />
									</a>
									
									{% block menuprodutos %}
									
										{% for prod in produtos %}
										    {% if prod.nom %}
								    		    <li><a href="{{path('detalhe_produto', {'id' : prod.id })}}">{{prod.nom}}</a></li>
										    {% endif %}
										{% endfor %}
									
									{% endblock %}
							
									<p>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget.
									odio eleifend. Duis commodo fringilla commodo. Aliquam erat volutpat. Vestibulum
									facilisis leo magna. Cras sit amet urna eros, id egestas urna. Quisque aliquam
									tempus euismod. Vestibulum ante ipsum primis in faucibus.</p>
									<p>Phasellus nisl nisl, varius id porttitor sed, pellentesque ac orci. Pellentesque
									habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi
									bibendum justo sed mauris vehicula malesuada aliquam elit imperdiet. Aliquam eu nibh
									lorem, eget gravida mi. Duis odio diam, luctus et vulputate vitae, vehicula ac dolor.
									Pellentesque at urna eget tellus lobortis ultrices sed non erat. Donec eget erat non
									magna volutpat malesuada quis eget eros. Nullam sodales cursus sapien, id consequat
									leo suscipit ut. Praesent id turpis vitae turpis pretium ultricies. Vestibulum sit
									amet risus elit.</p>
								</article>
							</div>

					</div>
				</div>

			<!-- Highlights -->
			{% block highlights %}
			{% endblock %}
				
{% endblock %}